kind: Pod
apiVersion: v1
metadata:
 name: annotation-example
 annotations:
  description: This is the example of annotation..
spec:
 containers:
  - name: c00
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo This is the example of annotation; sleep 8; done"]